[build-system]
requires = ["scikit-build-core", "cython >= 3.0"]
build-backend = "scikit_build_core.build"

[project]
name = "pyncbitk"
version = "0.0.1"
requires-python = ">=3.7"

[tool.cibuildwheel]
build-verbosity = 1

[tool.scikit-build]
build-dir = "build/{build_type}/{wheel_tag}"
cmake.build-type = "Release"
editable.rebuild = true
editable.verbose=false

[tool.scikit-build.cmake.define]
PYNCBITK_INSTALL_LIBS = { env = "PYNCBITK_INSTALL_LIBS", default = true }
PYNCBITK_DISABLE_SSE4 = { env = "PYNCBITK_DISABLE_SSE4", default = false }

[[tool.scikit-build.overrides]]
if.state = "editable"
cmake.build-type = "Debug"

[[tool.scikit-build.overrides]]
if.env.CIBUILDWHEEL = "ON"
cmake.define.PYNCBITK_INSTALL_LIBS = false
