[build-system]
requires = ["scikit-build-core", "cython"]
build-backend = "scikit_build_core.build"

[project]
name = "pyncbitk"
version = "0.0.1"

[tool.scikit-build]
build-dir = "build/{build_type}/{wheel_tag}"
cmake.build-type = "Release"
