[build-system]
build-backend = "scikit_build_core.build"
requires = [
    "scikit-build-core>=0.10.0", "cython >=3.0", "pyncbitk-runtime~=29.6.0.0a1",
]

[project]
name = "pyncbitk"
version = "0.1.0-alpha.3"
description = "Cython bindings and Python interface to the NCBI C++ Toolkit."
readme = "README.md"
requires-python = ">=3.7"
license = { file = "COPYING" }
authors = [
  { name = "Martin Larralde", email = "martin.larralde@embl.de" },
]
keywords = ["bioinformatics", "blast", "sequence", "alignment", "ncbi"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: C++",
    "Programming Language :: Cython",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Typing :: Typed",
]
dependencies=[
    "pyncbitk-runtime~=29.6.0.0a1"
]

[project.urls]
"Documentation" = "https://pyncbitk.readthedocs.io/en/stable/"
"Bug Tracker" = "https://github.com/althonos/pyncbitk/issues"
"Changelog" = "https://github.com/althonos/pyncbitk/blob/master/CHANGELOG.md"
"Coverage" = "https://codecov.io/gh/althonos/pyncbitk/"
"Builds" = "https://github.com/althonos/pyncbitk/actions"
"PyPI" = "https://pypi.org/project/pyncbitk"

[tool.scikit-build]
build-dir = "build/{build_type}"
wheel.py-api = "cp311"
cmake.build-type = "Release"
editable.rebuild = true
editable.verbose = false

[[tool.scikit-build.overrides]]
if.state = "editable"
cmake.build-type = "Debug"

[[tool.scikit-build-overrides]]
if.env.SCCACHE = true
cmake.define.CMAKE_C_COMPILER_LAUNCHER = "sccache"
cmake.define.CMAKE_CXX_COMPILER_LAUNCHER = "sccache"

[[tool.scikit-build-overrides]]
if.env.MOLD = true
cmake.define.CMAKE_LINKER_TYPE = "mold"

[tool.cibuildwheel]
build-frontend = { name = "build", args = [] }
build-verbosity = 1
test-command = "cd {project} && python -m unittest tests -v"
manylinux-x86_64-image = "quay.io/pypa/manylinux_2_34_x86_64"

[tool.cibuildwheel.macos]
environment = { MACOSX_DEPLOYMENT_TARGET = "10.12" }
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.linux]
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel} --exclude \\*"
