name: Compile runtime

on: workflow_dispatch

jobs:

  wheel-linux-x86_64:
    name: Build Linux wheels (x86-64)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v3.2.1
      env:
        CIBW_ARCHS: x86_64
        CIBW_BUILD: 'cp312-manylinux_x86_64'
        CIBW_BUILD_VERBOSITY: 2
      with:
        output-dir: dist
        package-dir: runtime
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-manylinux_x86_64
        path: dist/*

  sdist:
    runs-on: ubuntu-latest
    name: Build source distribution
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install build requirements
      run: python -m pip install -r .github/workflows/requirements.txt
    - name: Build source distribution
      run: python -m build -s ./runtime
    - name: Store built source distribution
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*
