name: Build

on:
  - push
  - pull_request

jobs:

  test_linux:
    name: Test (Linux)
    runs-on: ubuntu-22.04
    env:
      OS: Linux
    strategy:
      fail-fast: false
      matrix:
        include:
        - python-version: 3.8
          python-release: v3.8
          python-impl: CPython
        - python-version: 3.9
          python-release: v3.9
          python-impl: CPython
        - python-version: '3.10'
          python-release: v3.10
          python-impl: CPython
        - python-version: 3.11
          python-release: v3.11
          python-impl: CPython
        - python-version: 3.12
          python-release: v3.12
          python-impl: CPython
        - python-version: 3.13
          python-release: v3.13
          python-impl: CPython
        - python-version: 3.14
          python-release: v3.14
          python-impl: CPython
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: python -m pip install -U pip wheel setuptools
    - name: Install Python requirements
      run: python -m pip install -r .github/workflows/requirements.txt
    - name: Build and install package
      run: python -m pip install -v . --no-build-isolation
    - name: Test package
      run: python -m unittest tests -vv

  test_osx:
    name: Test (OSX)
    runs-on: macos-latest
    env:
      OS: OSX
    strategy:
      fail-fast: false
      matrix:
        include:
        - python-version: 3.8
          python-release: v3.8
          python-impl: CPython
        - python-version: 3.9
          python-release: v3.9
          python-impl: CPython
        - python-version: '3.10'
          python-release: v3.10
          python-impl: CPython
        - python-version: '3.11'
          python-release: v3.11
          python-impl: CPython
        - python-version: '3.12'
          python-release: v3.12
          python-impl: CPython
        - python-version: 3.13
          python-release: v3.13
          python-impl: CPython
        - python-version: 3.14
          python-release: v3.14
          python-impl: CPython
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: python -m pip install -U pip wheel setuptools
    - name: Install Python requirements
      run: python -m pip install -r .github/workflows/requirements.txt
    - name: Build and install package
      run: python -m pip install -v . --no-build-isolation
    - name: Test package
      run: python -m unittest tests -vv

  sdist:
    runs-on: ubuntu-latest
    name: Build source distribution
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install build requirements
      run: python -m pip install -r .github/workflows/requirements.txt
    - name: Build source distribution
      run: python -m build -s .
    - name: Store built source distribution
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*
